version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_HOST=http://backend:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8000
    networks:
      - chat-network
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./langchain
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ~/.oci:/root/.oci
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - chat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  chat-network:
    driver: bridge

volumes:
  oci-config: